sudo: required

language: python

matrix:
  include:
  python:
  - python: "2.7"
    env: PYTHON_VERSION=python2
  - python: "3.6"
    env: PYTHON_VERSION=python3

services:
- docker

install:
- make build

script:
- make git-attributes
- make lint
- make test
- make doc
- touch doc/build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: improve-project
  local_dir: _build/html/
