sudo: required

language: python

matrix:
  include:
  python:
  - python: "2.7"
    env: PYTHON_VERSION=python2
  - python: "3.6"
    env: PYTHON_VERSION=python3

services:
- docker

install:
- make build

script:
- make git-attributes
- make lint
- make test
- make doc

deploy:
  provider: script
  script: sphinx-versioning push doc/source/ gh-pages doc
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
    repo: vvmruder/pyramid_georest
    python: '3.6'
