# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class APIKeySecurityScheme(object):
    in = attr.ib(metadata={"schema_property_name": "in"})
    name = attr.ib(metadata={"schema_property_name": "name"})
    type = attr.ib(metadata={"schema_property_name": "type"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
