# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Contact(object):
    email = attr.ib(default=None, metadata={"schema_property_name": "email"})
    name = attr.ib(default=None, metadata={"schema_property_name": "name"})
    url = attr.ib(default=None, metadata={"schema_property_name": "url"})
