# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Discriminator(object):
    property_name = attr.ib(metadata={"schema_property_name": "propertyName"})
    mapping = attr.ib(default=None, metadata={"schema_property_name": "mapping"})
