# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Encoding(object):
    allow_reserved = attr.ib(default=None, metadata={"schema_property_name": "allowReserved"})
    content_type = attr.ib(default=None, metadata={"schema_property_name": "contentType"})
    explode = attr.ib(default=None, metadata={"schema_property_name": "explode"})
    headers = attr.ib(default=None, metadata={"schema_property_name": "headers"})
    style = attr.ib(default=None, metadata={"schema_property_name": "style"})
