# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Example(object):
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    external_value = attr.ib(default=None, metadata={"schema_property_name": "externalValue"})
    summary = attr.ib(default=None, metadata={"schema_property_name": "summary"})
    value = attr.ib(default=None, metadata={"schema_property_name": "value"})
