# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class HTTPSecurityScheme(object):
    scheme = attr.ib(metadata={"schema_property_name": "scheme"})
    type = attr.ib(metadata={"schema_property_name": "type"})
    bearer_format = attr.ib(default=None, metadata={"schema_property_name": "bearerFormat"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
