# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class ImplicitOAuthFlow(object):
    authorization_url = attr.ib(metadata={"schema_property_name": "authorizationUrl"})
    scopes = attr.ib(metadata={"schema_property_name": "scopes"})
    refresh_url = attr.ib(default=None, metadata={"schema_property_name": "refreshUrl"})
