# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Info(object):
    title = attr.ib(metadata={"schema_property_name": "title"})
    version = attr.ib(metadata={"schema_property_name": "version"})
    contact = attr.ib(default=None, metadata={"schema_property_name": "contact"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    license = attr.ib(default=None, metadata={"schema_property_name": "license"})
    terms_of_service = attr.ib(default=None, metadata={"schema_property_name": "termsOfService"})
