# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Link(object):
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    operation_id = attr.ib(default=None, metadata={"schema_property_name": "operationId"})
    operation_ref = attr.ib(default=None, metadata={"schema_property_name": "operationRef"})
    parameters = attr.ib(default=None, metadata={"schema_property_name": "parameters"})
    request_body = attr.ib(default=None, metadata={"schema_property_name": "requestBody"})
    server = attr.ib(default=None, metadata={"schema_property_name": "server"})
