# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class MediaType(object):
    encoding = attr.ib(default=None, metadata={"schema_property_name": "encoding"})
    example = attr.ib(default=None, metadata={"schema_property_name": "example"})
    examples = attr.ib(default=None, metadata={"schema_property_name": "examples"})
    schema = attr.ib(default=None, metadata={"schema_property_name": "schema"})
