# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class OAuthFlows(object):
    authorization_code = attr.ib(default=None, metadata={"schema_property_name": "authorizationCode"})
    client_credentials = attr.ib(default=None, metadata={"schema_property_name": "clientCredentials"})
    implicit = attr.ib(default=None, metadata={"schema_property_name": "implicit"})
    password = attr.ib(default=None, metadata={"schema_property_name": "password"})
