# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class OAuth2SecurityScheme(object):
    flows = attr.ib(metadata={"schema_property_name": "flows"})
    type = attr.ib(metadata={"schema_property_name": "type"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
