# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Operation(object):
    responses = attr.ib(metadata={"schema_property_name": "responses"})
    callbacks = attr.ib(default=None, metadata={"schema_property_name": "callbacks"})
    deprecated = attr.ib(default=None, metadata={"schema_property_name": "deprecated"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    external_docs = attr.ib(default=None, metadata={"schema_property_name": "externalDocs"})
    operation_id = attr.ib(default=None, metadata={"schema_property_name": "operationId"})
    parameters = attr.ib(default=None, metadata={"schema_property_name": "parameters"})
    request_body = attr.ib(default=None, metadata={"schema_property_name": "requestBody"})
    security = attr.ib(default=None, metadata={"schema_property_name": "security"})
    servers = attr.ib(default=None, metadata={"schema_property_name": "servers"})
    summary = attr.ib(default=None, metadata={"schema_property_name": "summary"})
    tags = attr.ib(default=None, metadata={"schema_property_name": "tags"})
