# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class OpenApiDocument(object):
    """Validation schema for OpenAPI Specification 3.0.X."""

    info = attr.ib(metadata={"schema_property_name": "info"})
    openapi = attr.ib(metadata={"schema_property_name": "openapi"})
    paths = attr.ib(metadata={"schema_property_name": "paths"})
    components = attr.ib(default=None, metadata={"schema_property_name": "components"})
    external_docs = attr.ib(default=None, metadata={"schema_property_name": "externalDocs"})
    security = attr.ib(default=None, metadata={"schema_property_name": "security"})
    servers = attr.ib(default=None, metadata={"schema_property_name": "servers"})
    tags = attr.ib(default=None, metadata={"schema_property_name": "tags"})
