# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class OpenIdConnectSecurityScheme(object):
    open_id_connect_url = attr.ib(metadata={"schema_property_name": "openIdConnectUrl"})
    type = attr.ib(metadata={"schema_property_name": "type"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
