# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Parameter(object):
    in = attr.ib(metadata={"schema_property_name": "in"})
    name = attr.ib(metadata={"schema_property_name": "name"})
    allow_empty_value = attr.ib(default=None, metadata={"schema_property_name": "allowEmptyValue"})
    allow_reserved = attr.ib(default=None, metadata={"schema_property_name": "allowReserved"})
    content = attr.ib(default=None, metadata={"schema_property_name": "content"})
    deprecated = attr.ib(default=None, metadata={"schema_property_name": "deprecated"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    example = attr.ib(default=None, metadata={"schema_property_name": "example"})
    examples = attr.ib(default=None, metadata={"schema_property_name": "examples"})
    explode = attr.ib(default=None, metadata={"schema_property_name": "explode"})
    required = attr.ib(default=None, metadata={"schema_property_name": "required"})
    schema = attr.ib(default=None, metadata={"schema_property_name": "schema"})
    style = attr.ib(default=None, metadata={"schema_property_name": "style"})
