# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class PathItem(object):
    $ref = attr.ib(default=None, metadata={"schema_property_name": "$ref"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    parameters = attr.ib(default=None, metadata={"schema_property_name": "parameters"})
    servers = attr.ib(default=None, metadata={"schema_property_name": "servers"})
    summary = attr.ib(default=None, metadata={"schema_property_name": "summary"})
