# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class RequestBody(object):
    content = attr.ib(metadata={"schema_property_name": "content"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    required = attr.ib(default=None, metadata={"schema_property_name": "required"})
