# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Response(object):
    description = attr.ib(metadata={"schema_property_name": "description"})
    content = attr.ib(default=None, metadata={"schema_property_name": "content"})
    headers = attr.ib(default=None, metadata={"schema_property_name": "headers"})
    links = attr.ib(default=None, metadata={"schema_property_name": "links"})
