# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class SchemaXORContent(object):
    """Schema and content are mutually exclusive, at least one is required"""

    pass
