# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class ServerVariable(object):
    default = attr.ib(metadata={"schema_property_name": "default"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    enum = attr.ib(default=None, metadata={"schema_property_name": "enum"})
