# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class Tag(object):
    name = attr.ib(metadata={"schema_property_name": "name"})
    description = attr.ib(default=None, metadata={"schema_property_name": "description"})
    external_docs = attr.ib(default=None, metadata={"schema_property_name": "externalDocs"})
