# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class XML(object):
    attribute = attr.ib(default=None, metadata={"schema_property_name": "attribute"})
    name = attr.ib(default=None, metadata={"schema_property_name": "name"})
    namespace = attr.ib(default=None, metadata={"schema_property_name": "namespace"})
    prefix = attr.ib(default=None, metadata={"schema_property_name": "prefix"})
    wrapped = attr.ib(default=None, metadata={"schema_property_name": "wrapped"})
